/**
 * BAL101.jsx - Production Handcrafted Brain Arrow Level
 * Generated by Brain Arrow Studio Editor
 */

const BAL101 = {
  "id": 101,
  "name": "Custom Level 101",
  "difficulty": "Easy",
  "moveCount": 10,
  "moves": 10,
  "gridSize": 10,
  "size": {
    "rows": 10,
    "cols": 10
  },
  "occupancy": "0%",
  "theme": {
    "name": "default",
    "color": "#0f172a",
    "bg": "#f8fafc",
    "diff": "Easy"
  },
  "arrows": [],
  "board": [],
  "solution": []
};

export default BAL101;
