/**
 * BAL4.jsx - Production Handcrafted Brain Arrow Level
 * Generated by Brain Arrow Studio Editor
 */

const BAL4 = {
  "id": 4,
  "name": "Custom Level 4",
  "difficulty": "Easy",
  "moveCount": 10,
  "moves": 10,
  "gridSize": 8,
  "size": {
    "rows": 8,
    "cols": 8
  },
  "occupancy": "100%",
  "theme": {
    "name": "default",
    "color": "#0f172a",
    "bg": "#f8fafc",
    "diff": "Easy"
  },
  "arrows": [
    {
      "id": "a_1786206072154_867",
      "direction": "UP",
      "color": "#0f172a",
      "vertices": [
        {
          "r": 6,
          "c": 0
        },
        {
          "r": 7,
          "c": 0
        },
        {
          "r": 7,
          "c": 1
        },
        {
          "r": 7,
          "c": 2
        },
        {
          "r": 7,
          "c": 3
        },
        {
          "r": 7,
          "c": 4
        },
        {
          "r": 7,
          "c": 5
        },
        {
          "r": 7,
          "c": 6
        },
        {
          "r": 7,
          "c": 7
        },
        {
          "r": 6,
          "c": 7
        },
        {
          "r": 5,
          "c": 7
        },
        {
          "r": 4,
          "c": 7
        },
        {
          "r": 3,
          "c": 7
        },
        {
          "r": 2,
          "c": 7
        },
        {
          "r": 1,
          "c": 7
        },
        {
          "r": 0,
          "c": 7
        },
        {
          "r": 0,
          "c": 6
        },
        {
          "r": 0,
          "c": 5
        },
        {
          "r": 0,
          "c": 4
        },
        {
          "r": 1,
          "c": 4
        },
        {
          "r": 2,
          "c": 4
        },
        {
          "r": 3,
          "c": 4
        },
        {
          "r": 4,
          "c": 4
        },
        {
          "r": 4,
          "c": 3
        },
        {
          "r": 3,
          "c": 3
        },
        {
          "r": 2,
          "c": 3
        },
        {
          "r": 1,
          "c": 3
        },
        {
          "r": 0,
          "c": 3
        }
      ],
      "pieces": [
        {
          "r": 6,
          "c": 0,
          "type": "DEAD_END",
          "rotation": 90
        },
        {
          "r": 7,
          "c": 0,
          "type": "CORNER",
          "rotation": 90
        },
        {
          "r": 7,
          "c": 1,
          "type": "STRAIGHT",
          "rotation": 0
        },
        {
          "r": 7,
          "c": 2,
          "type": "STRAIGHT",
          "rotation": 0
        },
        {
          "r": 7,
          "c": 3,
          "type": "STRAIGHT",
          "rotation": 0
        },
        {
          "r": 7,
          "c": 4,
          "type": "STRAIGHT",
          "rotation": 0
        },
        {
          "r": 7,
          "c": 5,
          "type": "STRAIGHT",
          "rotation": 0
        },
        {
          "r": 7,
          "c": 6,
          "type": "STRAIGHT",
          "rotation": 0
        },
        {
          "r": 7,
          "c": 7,
          "type": "CORNER",
          "rotation": 0
        },
        {
          "r": 6,
          "c": 7,
          "type": "STRAIGHT",
          "rotation": 90
        },
        {
          "r": 5,
          "c": 7,
          "type": "STRAIGHT",
          "rotation": 90
        },
        {
          "r": 4,
          "c": 7,
          "type": "STRAIGHT",
          "rotation": 90
        },
        {
          "r": 3,
          "c": 7,
          "type": "STRAIGHT",
          "rotation": 90
        },
        {
          "r": 2,
          "c": 7,
          "type": "STRAIGHT",
          "rotation": 90
        },
        {
          "r": 1,
          "c": 7,
          "type": "STRAIGHT",
          "rotation": 90
        },
        {
          "r": 0,
          "c": 7,
          "type": "CORNER",
          "rotation": 270
        },
        {
          "r": 0,
          "c": 6,
          "type": "STRAIGHT",
          "rotation": 0
        },
        {
          "r": 0,
          "c": 5,
          "type": "STRAIGHT",
          "rotation": 0
        },
        {
          "r": 0,
          "c": 4,
          "type": "CORNER",
          "rotation": 180
        },
        {
          "r": 1,
          "c": 4,
          "type": "STRAIGHT",
          "rotation": 90
        },
        {
          "r": 2,
          "c": 4,
          "type": "STRAIGHT",
          "rotation": 90
        },
        {
          "r": 3,
          "c": 4,
          "type": "STRAIGHT",
          "rotation": 90
        },
        {
          "r": 4,
          "c": 4,
          "type": "CORNER",
          "rotation": 0
        },
        {
          "r": 4,
          "c": 3,
          "type": "CORNER",
          "rotation": 90
        },
        {
          "r": 3,
          "c": 3,
          "type": "STRAIGHT",
          "rotation": 90
        },
        {
          "r": 2,
          "c": 3,
          "type": "STRAIGHT",
          "rotation": 90
        },
        {
          "r": 1,
          "c": 3,
          "type": "STRAIGHT",
          "rotation": 90
        },
        {
          "r": 0,
          "c": 3,
          "type": "ARROW_HEAD",
          "rotation": 270,
          "short": false
        }
      ]
    },
    {
      "id": "a_1786206090681_513",
      "direction": "UP",
      "color": "#0f172a",
      "vertices": [
        {
          "r": 5,
          "c": 5
        },
        {
          "r": 4,
          "c": 5
        },
        {
          "r": 3,
          "c": 5
        }
      ],
      "pieces": [
        {
          "r": 5,
          "c": 5,
          "type": "DEAD_END",
          "rotation": 270
        },
        {
          "r": 4,
          "c": 5,
          "type": "STRAIGHT",
          "rotation": 90
        },
        {
          "r": 3,
          "c": 5,
          "type": "ARROW_HEAD",
          "rotation": 270,
          "short": false
        }
      ]
    },
    {
      "id": "a_1786206123369_750",
      "direction": "RIGHT",
      "color": "#0f172a",
      "vertices": [
        {
          "r": 5,
          "c": 3
        },
        {
          "r": 5,
          "c": 4
        },
        {
          "r": 6,
          "c": 4
        },
        {
          "r": 6,
          "c": 5
        },
        {
          "r": 6,
          "c": 6
        },
        {
          "r": 5,
          "c": 6
        },
        {
          "r": 4,
          "c": 6
        },
        {
          "r": 3,
          "c": 6
        },
        {
          "r": 2,
          "c": 6
        },
        {
          "r": 2,
          "c": 5
        },
        {
          "r": 1,
          "c": 5
        },
        {
          "r": 1,
          "c": 6
        }
      ],
      "pieces": [
        {
          "r": 5,
          "c": 3,
          "type": "DEAD_END",
          "rotation": 0
        },
        {
          "r": 5,
          "c": 4,
          "type": "CORNER",
          "rotation": 270
        },
        {
          "r": 6,
          "c": 4,
          "type": "CORNER",
          "rotation": 90
        },
        {
          "r": 6,
          "c": 5,
          "type": "STRAIGHT",
          "rotation": 0
        },
        {
          "r": 6,
          "c": 6,
          "type": "CORNER",
          "rotation": 0
        },
        {
          "r": 5,
          "c": 6,
          "type": "STRAIGHT",
          "rotation": 90
        },
        {
          "r": 4,
          "c": 6,
          "type": "STRAIGHT",
          "rotation": 90
        },
        {
          "r": 3,
          "c": 6,
          "type": "STRAIGHT",
          "rotation": 90
        },
        {
          "r": 2,
          "c": 6,
          "type": "CORNER",
          "rotation": 270
        },
        {
          "r": 2,
          "c": 5,
          "type": "CORNER",
          "rotation": 90
        },
        {
          "r": 1,
          "c": 5,
          "type": "CORNER",
          "rotation": 180
        },
        {
          "r": 1,
          "c": 6,
          "type": "ARROW_HEAD",
          "rotation": 0,
          "short": false
        }
      ]
    },
    {
      "id": "a_1786206144093_869",
      "direction": "RIGHT",
      "color": "#0f172a",
      "vertices": [
        {
          "r": 2,
          "c": 2
        },
        {
          "r": 3,
          "c": 2
        },
        {
          "r": 4,
          "c": 2
        },
        {
          "r": 4,
          "c": 1
        },
        {
          "r": 3,
          "c": 1
        },
        {
          "r": 2,
          "c": 1
        },
        {
          "r": 1,
          "c": 1
        },
        {
          "r": 1,
          "c": 2
        }
      ],
      "pieces": [
        {
          "r": 2,
          "c": 2,
          "type": "DEAD_END",
          "rotation": 90
        },
        {
          "r": 3,
          "c": 2,
          "type": "STRAIGHT",
          "rotation": 90
        },
        {
          "r": 4,
          "c": 2,
          "type": "CORNER",
          "rotation": 0
        },
        {
          "r": 4,
          "c": 1,
          "type": "CORNER",
          "rotation": 90
        },
        {
          "r": 3,
          "c": 1,
          "type": "STRAIGHT",
          "rotation": 90
        },
        {
          "r": 2,
          "c": 1,
          "type": "STRAIGHT",
          "rotation": 90
        },
        {
          "r": 1,
          "c": 1,
          "type": "CORNER",
          "rotation": 180
        },
        {
          "r": 1,
          "c": 2,
          "type": "ARROW_HEAD",
          "rotation": 0,
          "short": false
        }
      ]
    },
    {
      "id": "a_1786206190939_309",
      "direction": "DOWN",
      "color": "#0f172a",
      "vertices": [
        {
          "r": 0,
          "c": 2
        },
        {
          "r": 0,
          "c": 1
        },
        {
          "r": 0,
          "c": 0
        },
        {
          "r": 1,
          "c": 0
        },
        {
          "r": 2,
          "c": 0
        },
        {
          "r": 3,
          "c": 0
        },
        {
          "r": 4,
          "c": 0
        },
        {
          "r": 5,
          "c": 0
        },
        {
          "r": 5,
          "c": 1
        },
        {
          "r": 6,
          "c": 1
        }
      ],
      "pieces": [
        {
          "r": 0,
          "c": 2,
          "type": "DEAD_END",
          "rotation": 180
        },
        {
          "r": 0,
          "c": 1,
          "type": "STRAIGHT",
          "rotation": 0
        },
        {
          "r": 0,
          "c": 0,
          "type": "CORNER",
          "rotation": 180
        },
        {
          "r": 1,
          "c": 0,
          "type": "STRAIGHT",
          "rotation": 90
        },
        {
          "r": 2,
          "c": 0,
          "type": "STRAIGHT",
          "rotation": 90
        },
        {
          "r": 3,
          "c": 0,
          "type": "STRAIGHT",
          "rotation": 90
        },
        {
          "r": 4,
          "c": 0,
          "type": "STRAIGHT",
          "rotation": 90
        },
        {
          "r": 5,
          "c": 0,
          "type": "CORNER",
          "rotation": 90
        },
        {
          "r": 5,
          "c": 1,
          "type": "CORNER",
          "rotation": 270
        },
        {
          "r": 6,
          "c": 1,
          "type": "ARROW_HEAD",
          "rotation": 90,
          "short": false
        }
      ]
    },
    {
      "id": "a_1786206193799_451",
      "direction": "UP",
      "color": "#0f172a",
      "vertices": [
        {
          "r": 6,
          "c": 3
        },
        {
          "r": 6,
          "c": 2
        },
        {
          "r": 5,
          "c": 2
        }
      ],
      "pieces": [
        {
          "r": 6,
          "c": 3,
          "type": "DEAD_END",
          "rotation": 180
        },
        {
          "r": 6,
          "c": 2,
          "type": "CORNER",
          "rotation": 90
        },
        {
          "r": 5,
          "c": 2,
          "type": "ARROW_HEAD",
          "rotation": 270,
          "short": false
        }
      ]
    }
  ],
  "board": [
    {
      "id": "a_1786206072154_867",
      "direction": "UP",
      "color": "#0f172a",
      "vertices": [
        {
          "r": 6,
          "c": 0
        },
        {
          "r": 7,
          "c": 0
        },
        {
          "r": 7,
          "c": 1
        },
        {
          "r": 7,
          "c": 2
        },
        {
          "r": 7,
          "c": 3
        },
        {
          "r": 7,
          "c": 4
        },
        {
          "r": 7,
          "c": 5
        },
        {
          "r": 7,
          "c": 6
        },
        {
          "r": 7,
          "c": 7
        },
        {
          "r": 6,
          "c": 7
        },
        {
          "r": 5,
          "c": 7
        },
        {
          "r": 4,
          "c": 7
        },
        {
          "r": 3,
          "c": 7
        },
        {
          "r": 2,
          "c": 7
        },
        {
          "r": 1,
          "c": 7
        },
        {
          "r": 0,
          "c": 7
        },
        {
          "r": 0,
          "c": 6
        },
        {
          "r": 0,
          "c": 5
        },
        {
          "r": 0,
          "c": 4
        },
        {
          "r": 1,
          "c": 4
        },
        {
          "r": 2,
          "c": 4
        },
        {
          "r": 3,
          "c": 4
        },
        {
          "r": 4,
          "c": 4
        },
        {
          "r": 4,
          "c": 3
        },
        {
          "r": 3,
          "c": 3
        },
        {
          "r": 2,
          "c": 3
        },
        {
          "r": 1,
          "c": 3
        },
        {
          "r": 0,
          "c": 3
        }
      ],
      "pieces": [
        {
          "r": 6,
          "c": 0,
          "type": "DEAD_END",
          "rotation": 90
        },
        {
          "r": 7,
          "c": 0,
          "type": "CORNER",
          "rotation": 90
        },
        {
          "r": 7,
          "c": 1,
          "type": "STRAIGHT",
          "rotation": 0
        },
        {
          "r": 7,
          "c": 2,
          "type": "STRAIGHT",
          "rotation": 0
        },
        {
          "r": 7,
          "c": 3,
          "type": "STRAIGHT",
          "rotation": 0
        },
        {
          "r": 7,
          "c": 4,
          "type": "STRAIGHT",
          "rotation": 0
        },
        {
          "r": 7,
          "c": 5,
          "type": "STRAIGHT",
          "rotation": 0
        },
        {
          "r": 7,
          "c": 6,
          "type": "STRAIGHT",
          "rotation": 0
        },
        {
          "r": 7,
          "c": 7,
          "type": "CORNER",
          "rotation": 0
        },
        {
          "r": 6,
          "c": 7,
          "type": "STRAIGHT",
          "rotation": 90
        },
        {
          "r": 5,
          "c": 7,
          "type": "STRAIGHT",
          "rotation": 90
        },
        {
          "r": 4,
          "c": 7,
          "type": "STRAIGHT",
          "rotation": 90
        },
        {
          "r": 3,
          "c": 7,
          "type": "STRAIGHT",
          "rotation": 90
        },
        {
          "r": 2,
          "c": 7,
          "type": "STRAIGHT",
          "rotation": 90
        },
        {
          "r": 1,
          "c": 7,
          "type": "STRAIGHT",
          "rotation": 90
        },
        {
          "r": 0,
          "c": 7,
          "type": "CORNER",
          "rotation": 270
        },
        {
          "r": 0,
          "c": 6,
          "type": "STRAIGHT",
          "rotation": 0
        },
        {
          "r": 0,
          "c": 5,
          "type": "STRAIGHT",
          "rotation": 0
        },
        {
          "r": 0,
          "c": 4,
          "type": "CORNER",
          "rotation": 180
        },
        {
          "r": 1,
          "c": 4,
          "type": "STRAIGHT",
          "rotation": 90
        },
        {
          "r": 2,
          "c": 4,
          "type": "STRAIGHT",
          "rotation": 90
        },
        {
          "r": 3,
          "c": 4,
          "type": "STRAIGHT",
          "rotation": 90
        },
        {
          "r": 4,
          "c": 4,
          "type": "CORNER",
          "rotation": 0
        },
        {
          "r": 4,
          "c": 3,
          "type": "CORNER",
          "rotation": 90
        },
        {
          "r": 3,
          "c": 3,
          "type": "STRAIGHT",
          "rotation": 90
        },
        {
          "r": 2,
          "c": 3,
          "type": "STRAIGHT",
          "rotation": 90
        },
        {
          "r": 1,
          "c": 3,
          "type": "STRAIGHT",
          "rotation": 90
        },
        {
          "r": 0,
          "c": 3,
          "type": "ARROW_HEAD",
          "rotation": 270,
          "short": false
        }
      ]
    },
    {
      "id": "a_1786206090681_513",
      "direction": "UP",
      "color": "#0f172a",
      "vertices": [
        {
          "r": 5,
          "c": 5
        },
        {
          "r": 4,
          "c": 5
        },
        {
          "r": 3,
          "c": 5
        }
      ],
      "pieces": [
        {
          "r": 5,
          "c": 5,
          "type": "DEAD_END",
          "rotation": 270
        },
        {
          "r": 4,
          "c": 5,
          "type": "STRAIGHT",
          "rotation": 90
        },
        {
          "r": 3,
          "c": 5,
          "type": "ARROW_HEAD",
          "rotation": 270,
          "short": false
        }
      ]
    },
    {
      "id": "a_1786206123369_750",
      "direction": "RIGHT",
      "color": "#0f172a",
      "vertices": [
        {
          "r": 5,
          "c": 3
        },
        {
          "r": 5,
          "c": 4
        },
        {
          "r": 6,
          "c": 4
        },
        {
          "r": 6,
          "c": 5
        },
        {
          "r": 6,
          "c": 6
        },
        {
          "r": 5,
          "c": 6
        },
        {
          "r": 4,
          "c": 6
        },
        {
          "r": 3,
          "c": 6
        },
        {
          "r": 2,
          "c": 6
        },
        {
          "r": 2,
          "c": 5
        },
        {
          "r": 1,
          "c": 5
        },
        {
          "r": 1,
          "c": 6
        }
      ],
      "pieces": [
        {
          "r": 5,
          "c": 3,
          "type": "DEAD_END",
          "rotation": 0
        },
        {
          "r": 5,
          "c": 4,
          "type": "CORNER",
          "rotation": 270
        },
        {
          "r": 6,
          "c": 4,
          "type": "CORNER",
          "rotation": 90
        },
        {
          "r": 6,
          "c": 5,
          "type": "STRAIGHT",
          "rotation": 0
        },
        {
          "r": 6,
          "c": 6,
          "type": "CORNER",
          "rotation": 0
        },
        {
          "r": 5,
          "c": 6,
          "type": "STRAIGHT",
          "rotation": 90
        },
        {
          "r": 4,
          "c": 6,
          "type": "STRAIGHT",
          "rotation": 90
        },
        {
          "r": 3,
          "c": 6,
          "type": "STRAIGHT",
          "rotation": 90
        },
        {
          "r": 2,
          "c": 6,
          "type": "CORNER",
          "rotation": 270
        },
        {
          "r": 2,
          "c": 5,
          "type": "CORNER",
          "rotation": 90
        },
        {
          "r": 1,
          "c": 5,
          "type": "CORNER",
          "rotation": 180
        },
        {
          "r": 1,
          "c": 6,
          "type": "ARROW_HEAD",
          "rotation": 0,
          "short": false
        }
      ]
    },
    {
      "id": "a_1786206144093_869",
      "direction": "RIGHT",
      "color": "#0f172a",
      "vertices": [
        {
          "r": 2,
          "c": 2
        },
        {
          "r": 3,
          "c": 2
        },
        {
          "r": 4,
          "c": 2
        },
        {
          "r": 4,
          "c": 1
        },
        {
          "r": 3,
          "c": 1
        },
        {
          "r": 2,
          "c": 1
        },
        {
          "r": 1,
          "c": 1
        },
        {
          "r": 1,
          "c": 2
        }
      ],
      "pieces": [
        {
          "r": 2,
          "c": 2,
          "type": "DEAD_END",
          "rotation": 90
        },
        {
          "r": 3,
          "c": 2,
          "type": "STRAIGHT",
          "rotation": 90
        },
        {
          "r": 4,
          "c": 2,
          "type": "CORNER",
          "rotation": 0
        },
        {
          "r": 4,
          "c": 1,
          "type": "CORNER",
          "rotation": 90
        },
        {
          "r": 3,
          "c": 1,
          "type": "STRAIGHT",
          "rotation": 90
        },
        {
          "r": 2,
          "c": 1,
          "type": "STRAIGHT",
          "rotation": 90
        },
        {
          "r": 1,
          "c": 1,
          "type": "CORNER",
          "rotation": 180
        },
        {
          "r": 1,
          "c": 2,
          "type": "ARROW_HEAD",
          "rotation": 0,
          "short": false
        }
      ]
    },
    {
      "id": "a_1786206190939_309",
      "direction": "DOWN",
      "color": "#0f172a",
      "vertices": [
        {
          "r": 0,
          "c": 2
        },
        {
          "r": 0,
          "c": 1
        },
        {
          "r": 0,
          "c": 0
        },
        {
          "r": 1,
          "c": 0
        },
        {
          "r": 2,
          "c": 0
        },
        {
          "r": 3,
          "c": 0
        },
        {
          "r": 4,
          "c": 0
        },
        {
          "r": 5,
          "c": 0
        },
        {
          "r": 5,
          "c": 1
        },
        {
          "r": 6,
          "c": 1
        }
      ],
      "pieces": [
        {
          "r": 0,
          "c": 2,
          "type": "DEAD_END",
          "rotation": 180
        },
        {
          "r": 0,
          "c": 1,
          "type": "STRAIGHT",
          "rotation": 0
        },
        {
          "r": 0,
          "c": 0,
          "type": "CORNER",
          "rotation": 180
        },
        {
          "r": 1,
          "c": 0,
          "type": "STRAIGHT",
          "rotation": 90
        },
        {
          "r": 2,
          "c": 0,
          "type": "STRAIGHT",
          "rotation": 90
        },
        {
          "r": 3,
          "c": 0,
          "type": "STRAIGHT",
          "rotation": 90
        },
        {
          "r": 4,
          "c": 0,
          "type": "STRAIGHT",
          "rotation": 90
        },
        {
          "r": 5,
          "c": 0,
          "type": "CORNER",
          "rotation": 90
        },
        {
          "r": 5,
          "c": 1,
          "type": "CORNER",
          "rotation": 270
        },
        {
          "r": 6,
          "c": 1,
          "type": "ARROW_HEAD",
          "rotation": 90,
          "short": false
        }
      ]
    },
    {
      "id": "a_1786206193799_451",
      "direction": "UP",
      "color": "#0f172a",
      "vertices": [
        {
          "r": 6,
          "c": 3
        },
        {
          "r": 6,
          "c": 2
        },
        {
          "r": 5,
          "c": 2
        }
      ],
      "pieces": [
        {
          "r": 6,
          "c": 3,
          "type": "DEAD_END",
          "rotation": 180
        },
        {
          "r": 6,
          "c": 2,
          "type": "CORNER",
          "rotation": 90
        },
        {
          "r": 5,
          "c": 2,
          "type": "ARROW_HEAD",
          "rotation": 270,
          "short": false
        }
      ]
    }
  ],
  "solution": [
    "a_1786206072154_867",
    "a_1786206123369_750",
    "a_1786206090681_513",
    "a_1786206144093_869",
    "a_1786206190939_309",
    "a_1786206193799_451"
  ]
};

export default BAL4;
